
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2
        
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
     
      - name: 🔧 Install package dependencies
        run: npm install
        
      - name: 🚀 Deploy
        run: npm run deploy