
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2
        
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
     
      - name: 🔧 Install package dependencies
        run: npm install
        
        - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploying to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
  
      # - name: 🚀 Deploy
      #   run: npm run deploy

      - name: 🚀 Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: 
          publish_dir: ./build